name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          # Build pectra-cli
          PECTRA_BINARY_NAME="pectra-cli"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            PECTRA_BINARY_NAME="${PECTRA_BINARY_NAME}.exe"
          fi
          go build -o $PECTRA_BINARY_NAME cmd/main.go

          # Build signer
          SIGNER_BINARY_NAME="signer"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            SIGNER_BINARY_NAME="${SIGNER_BINARY_NAME}.exe"
          fi
          go build -o $SIGNER_BINARY_NAME scripts/sign.go

          # Create dist directory and move binaries
          mkdir -p dist
          if [ "${{ matrix.goos }}" = "windows" ]; then
            mv $PECTRA_BINARY_NAME "dist/pectra-cli-${{ matrix.goos }}-${{ matrix.goarch }}.exe"
            mv $SIGNER_BINARY_NAME "dist/signer-${{ matrix.goos }}-${{ matrix.goarch }}.exe"
          else
            mv $PECTRA_BINARY_NAME "dist/pectra-cli-${{ matrix.goos }}-${{ matrix.goarch }}"
            mv $SIGNER_BINARY_NAME "dist/signer-${{ matrix.goos }}-${{ matrix.goarch }}"
          fi

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
